/* Progress screen: presentation and cache orchestration; calculations live in progress.js. */
let progressPeriod=localStorage.getItem('wt_progress_period')||'30d';
let progressGoal=Math.max(1,Number(localStorage.getItem('wt_week_goal')||3));
let progressMetric='weight';
let progressExercise='';
let progressCache=WorkoutProgress.createMemo();
let localMuscleOverrides=JSON.parse(localStorage.getItem('wt_muscle_groups_custom')||'{}');
let muscleMap={...WorkoutProgress.DEFAULT_EXERCISE_MUSCLES,...localMuscleOverrides};
let pendingGroupSync=false;
const muscleColors={'Грудь':'#df745d','Спина':'#527e9d','Ноги':'#78916b','Плечи':'#b28b4b','Руки':'#927ba8','Кор':'#688b83','Без группы':'#d5d2cc'};
function pEntries(){return WorkoutProgress.dateEntries(Object.values(state.sessions||{}),{yearForShortDates:2026,excludePullups:true});}
function pData(){const sessions=Object.values(state.sessions||{}),entries=pEntries(),days=WorkoutProgress.workoutDates(sessions,2026),asOf=WorkoutProgress.isoDate(todayStr(),2026)||'2026-10-05',key=[progressRevision,progressPeriod,progressGoal,JSON.stringify(muscleMap),entries.length,days.join(','),asOf].join('|');return progressCache.get(key,()=>({entries,days,period:WorkoutProgress.summarizePeriod(entries,progressPeriod,asOf,progressGoal,days),groups:WorkoutProgress.muscleDistribution(entries,muscleMap,...Object.values(WorkoutProgress.periodBounds(progressPeriod,asOf,entries)).slice(0,2)),records:WorkoutProgress.personalRecords(WorkoutProgress.workoutSeries(entries)),weekly:WorkoutProgress.weeklyDigest(entries,asOf,progressGoal,days),monthly:WorkoutProgress.monthlyDigest(entries,asOf,progressGoal,days),options:WorkoutProgress.getExerciseOptions(entries)}));}
function pFmt(n,d=0){return n===null||n===undefined||!Number.isFinite(n)?'—':Number(n).toLocaleString('ru-RU',{maximumFractionDigits:d,minimumFractionDigits:0});}
function pDate(d){return WorkoutProgress.dateLabel(d);}
function pEsc(x){return escapeHtml(x);}
function pDelta(n){if(n===null)return '<span class="p-delta neutral">— нет сравнения</span>';const up=n>0,down=n<0;return `<span class="p-delta ${up?'up':down?'down':'neutral'}">${up?'↑':down?'↓':'—'} ${pFmt(Math.abs(n),1)}%</span>`;}
function pSetStr(sets){return sets.map(s=>`${pFmt(s.weight??0,2)}×${pFmt(s.reps)}`).join(' · ');}
function renderStats(){
 const root=document.getElementById('progressRoot');if(!root)return;
 const data=pData(),period=data.period,bounds=period.bounds;
 if(!progressExercise||!data.options.some(x=>x.name===progressExercise))progressExercise=data.options[0]?.name||'';
 root.innerHTML=`<div class="p-period-row"><div class="p-periods" role="group" aria-label="Период">${Object.entries(WorkoutProgress.PERIODS).map(([k,v])=>`<button class="p-period ${k===progressPeriod?'active':''}" onclick="setProgressPeriod('${k}')">${v.label}</button>`).join('')}</div></div>
 <section class="p-section"><div class="p-section-head"><div><h2>Сводка за период</h2><p>${pDate(bounds.start)} — ${pDate(bounds.end)} · сравнение с таким же периодом</p></div></div><div class="p-summary-grid">${[['Тренировки',period.current.workouts,period.deltas.workouts,'шт'],['Тоннаж',pFmt(period.current.tonnage,1)+' кг',period.deltas.tonnage,''],['Подходы',period.current.sets,period.deltas.sets,'шт'],['Текущая серия',period.streak.current,period.deltas.currentStreak,'нед.'],['Лучшая серия',period.streak.best,period.deltas.bestStreak,'нед.']].map(x=>`<article class="p-card p-stat"><span>${x[0]}</span><strong>${x[1]}${x[3]?` <small>${x[3]}</small>`:''}</strong>${pDelta(x[2])}</article>`).join('')}</div></section>
 <section class="p-section"><div class="p-section-head"><div><h2>Регулярность</h2><p>${period.goalWeekPercent.toFixed(0)}% недель достигли цели</p></div><label class="p-goal">Цель <input type="number" min="1" max="14" value="${progressGoal}" onchange="setWeekGoal(this.value)"> / нед.</label></div><div class="p-card p-chart-card" id="weeklyChart"></div><div class="p-activity-host"><div class="p-section-head"><div><h3>Активность</h3><p>Календарь тренировок</p></div></div><div id="calendarChart"></div></div></section>
 <section class="p-section"><div class="p-section-head"><div><h2>Прогресс по упражнениям</h2><p>Выбери упражнение для подробной динамики</p></div></div><div class="p-card p-ex-picker"><label for="progressExercisePicker">Упражнение</label><input id="progressExercisePicker" list="progressExerciseOptions" value="${pEsc(progressExercise)}" placeholder="Поиск упражнения…" onchange="selectProgressExercise(this.value)"><datalist id="progressExerciseOptions">${data.options.map(o=>`<option value="${pEsc(o.name)}">${o.workouts} тренировок</option>`).join('')}</datalist></div><div id="exerciseProgress"></div></section>
 <section class="p-section"><div class="p-section-head"><div><h2>Личные рекорды</h2><p>Последние рекорды за выбранный период</p></div></div>${renderRecords(data.records.filter(r=>r.date>=bounds.start&&r.date<=bounds.end).slice(0,10))}</section>
 <section class="p-section"><div class="p-section-head"><div><h2>Объём по группам мышц</h2><p>Тоннаж и количество подходов</p></div></div>${renderMuscles(data)}</section>
 <section class="p-section"><div class="p-section-head"><div><h2>Итоги</h2><p>Неделя и текущий месяц</p></div></div><div class="p-digest-grid">${renderDigest('Итог недели',data.weekly)}${renderDigest('Итог месяца',data.monthly)}</div></section>`;
 renderWeeklyChart(period.weekly,progressGoal);renderExerciseProgress(data);renderCalendar();
}
function setProgressPeriod(value){progressPeriod=value;localStorage.setItem('wt_progress_period',value);renderStats();}
function setWeekGoal(value){progressGoal=Math.max(1,Math.min(14,Number(value)||3));localStorage.setItem('wt_week_goal',progressGoal);progressCache.clear();renderStats();}
function selectProgressExercise(value){progressExercise=value;renderStats();}
function renderWeeklyChart(weeks,goal){const host=document.getElementById('weeklyChart');if(!weeks.length){host.innerHTML='<div class="p-empty">Нет данных за выбранный период.</div>';return;}const W=680,H=205,pad={l:34,r:12,t:18,b:34},innerW=W-pad.l-pad.r,innerH=H-pad.t-pad.b,max=Math.max(goal,...weeks.map(x=>x.count),1),step=innerW/weeks.length,bw=Math.min(30,step*.56),gy=pad.t+innerH-(goal/max)*innerH;host.innerHTML=`<div class="p-chart-scroll"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Число тренировок в неделю и линия цели"><line x1="${pad.l}" x2="${W-pad.r}" y1="${gy}" y2="${gy}" stroke="#df745d" stroke-dasharray="5 4"/><text x="${pad.l}" y="${Math.max(12,gy-6)}" fill="#ad5948" font-size="11">Цель ${goal}</text>${weeks.map((w,i)=>{let x=pad.l+i*step+(step-bw)/2,h=w.count/max*innerH,y=pad.t+innerH-h;return `<g><rect x="${x}" y="${y}" width="${bw}" height="${h}" rx="5" fill="${w.met?'#191917':'#d9d7d1'}"><title>${pDate(w.boundedStart)}: ${w.count} тренировок, ${w.met?'цель достигнута':'цель не достигнута'}</title></rect>${weeks.length<14||i%Math.ceil(weeks.length/12)===0?`<text x="${x+bw/2}" y="${H-10}" text-anchor="middle" fill="#77746e" font-size="10">${pDate(w.weekStart)}</text>`:''}</g>`}).join('')}</svg></div><div class="p-legend"><span><i></i> Цель выполнена</span><span class="p-legend-target">— — Цель ${goal} тренировок в неделю</span></div>`;}
function renderExerciseProgress(data){const el=document.getElementById('exerciseProgress');if(!progressExercise){el.innerHTML='<div class="p-card p-empty">Добавь тренировку, чтобы увидеть прогресс.</div>';return;}const b=data.period.bounds,all=WorkoutProgress.summarizeExercise(data.entries,progressExercise,null,null,progressMetric),selected=WorkoutProgress.summarizeExercise(data.entries,progressExercise,b.start,b.end,progressMetric),opt=data.options.find(x=>x.name===progressExercise),isBody=selected.workouts.every(w=>w.maxWeight===null);const metric=isBody?'reps':progressMetric;progressMetric=metric;const series=WorkoutProgress.summarizeExercise(data.entries,progressExercise,b.start,b.end,metric).series;const stats=all.stats,first=stats.first,firstVal=first?WorkoutProgress.metricValue(first,metric):null,lastVal=all.workouts.length?WorkoutProgress.metricValue(all.workouts[all.workouts.length-1],metric):null,gain=firstVal!==null&&lastVal!==null?lastVal-firstVal:null,gainPct=firstVal>0&&gain!==null?gain/firstVal*100:null;
 el.innerHTML=`<div class="p-metric-switch">${(isBody?[['reps','Повторы']]:[['weight','Рабочий вес'],['1rm','Расчётный 1RM'],['volume','Тоннаж']]).map(x=>`<button class="${metric===x[0]?'active':''}" onclick="setProgressMetric('${x[0]}')">${x[1]}</button>`).join('')}</div>${series.length?`<div class="p-card p-ex-chart">${renderLineChart(series,metric)}<div class="p-chart-caption">${metric==='volume'?'Тоннаж за тренировку, кг':metric==='1rm'?'Расчётный 1RM по Эпли, кг':metric==='reps'?'Максимум повторений за тренировку':'Максимальный рабочий вес за тренировку, кг'}</div></div>`:'<div class="p-card p-empty">За этот период нет тренировок с выбранным упражнением.</div>'}<div class="p-summary-grid p-ex-cards">${[['Лучший подход',stats.bestWeight===null?'—':pFmt(stats.bestWeight,2)+' кг'],['Лучший 1RM',stats.best1RM===null?'—':pFmt(stats.best1RM,2)+' кг'],['Макс. повторений',stats.bestReps===null?'—':pFmt(stats.bestReps)],['Первая запись',first?`${pDate(first.date)} · ${firstVal===null?'—':pFmt(firstVal,2)+(metric==='reps'?' повт.':' кг')}`:'—'],['Прирост с первой',gain===null?'—':`${gain>=0?'+':''}${pFmt(gain,2)} ${metric==='reps'?'повт.':'кг'} · ${gainPct===null?'—':(gainPct>=0?'+':'')+pFmt(gainPct,1)+'%' }`]].map(x=>`<div class="p-card p-stat p-small-stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="p-card p-table-card"><h3>Последние тренировки</h3>${selected.lastTen.length?`<div class="p-table-scroll"><table class="p-table"><thead><tr><th>Дата</th><th>Подходы · вес×повторы</th><th>Тоннаж</th></tr></thead><tbody>${selected.lastTen.map(w=>`<tr><td>${pDate(w.date)}</td><td>${pSetStr(w.sets)}</td><td>${pFmt(w.tonnage,1)} кг</td></tr>`).join('')}</tbody></table></div>`:'<div class="p-empty">Пока нет тренировок с этим упражнением.</div>'}</div>`;
}
function setProgressMetric(metric){progressMetric=metric;renderStats();}
function showProgressPoint(date,value,metric,isPR){const label=metric==='reps'?'повторений':metric==='volume'?'кг тоннажа':'кг';showToast(`${pDate(date)} · ${pFmt(value,2)} ${label}${isPR?' · личный рекорд':''}`);}
function renderLineChart(series,metric){const points=series.filter(x=>x.value!==null);if(!points.length)return '<div class="p-empty">Нет применимых данных для графика.</div>';const W=680,H=220,pad=36,vals=points.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||Math.max(1,max*.08),xs=points.map((_,i)=>pad+i*(W-pad*2)/Math.max(1,points.length-1)),ys=points.map(p=>H-pad-(p.value-min)/range*(H-pad*2)),line=xs.map((x,i)=>`${x},${ys[i]}`).join(' ');return `<div class="p-chart-scroll"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="График ${metric}"><polyline points="${line}" fill="none" stroke="#191917" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${points.map((p,i)=>`<circle cx="${xs[i]}" cy="${ys[i]}" r="${p.isPR?7:5}" fill="${p.isPR?'#df745d':'#191917'}" stroke="#fff" stroke-width="2" tabindex="0" role="button" onclick="showProgressPoint('${p.date}',${p.value},'${metric}',${p.isPR})" onkeydown="if(event.key==='Enter'||event.key===' '){showProgressPoint('${p.date}',${p.value},'${metric}',${p.isPR})}"><title>${pDate(p.date)} · ${pFmt(p.value,2)}${metric==='reps'?' повторений':' кг'}${p.isPR?' · личный рекорд':''}</title></circle>`).join('')}<text x="${pad}" y="${H-8}" fill="#77746e" font-size="11">${pDate(points[0].date)}</text>${points.length>1?`<text x="${W-pad}" y="${H-8}" text-anchor="end" fill="#77746e" font-size="11">${pDate(points.at(-1).date)}</text>`:''}</svg></div>`;}
function renderRecords(records){if(!records.length)return '<div class="p-card p-empty">За выбранный период рекордов нет.</div>';const names={maxWeight:'Максимальный вес',repsAtWeight:'Повторы на этом весе',oneRM:'Расчётный 1RM',tonnage:'Тоннаж за тренировку'};return `<div class="p-card p-table-card"><div class="p-record-list">${records.map(r=>`<div class="p-record-row"><span class="p-record-dot" aria-hidden="true"></span><div><b>${pDate(r.date)} · ${pEsc(r.exercise)}</b><small>${names[r.type]}</small></div><strong>${r.oldValue===null?'—':pFmt(r.oldValue,2)} → ${pFmt(r.newValue,2)}${r.type==='repsAtWeight'?' повт.':' кг'}</strong></div>`).join('')}</div></div>`;}
function renderMuscles(data){const groups=data.groups.groups,total=groups.reduce((s,g)=>s+g.tonnage,0),shares=groups.map(g=>({...g,share:total?g.tonnage/total:0})),segments=[];let at=0;shares.forEach(g=>{let end=at+g.share*360;segments.push(`${muscleColors[g.group]} ${at}deg ${end}deg`);at=end;});const weeks=Math.max(WorkoutProgress.periodLengthWeeks(data.period.bounds.start,data.period.bounds.end),1),averages=WorkoutProgress.groupWeeklyAverages(data.groups.groups,weeks),imbalances=WorkoutProgress.muscleImbalances(groups);return `<div class="p-card p-muscle-grid"><div><h3>Доля тоннажа</h3>${total?`<div class="p-donut" style="background:conic-gradient(${segments.join(',')})"><div><b>${pFmt(total,0)}</b><span>кг всего</span></div></div><div class="p-muscle-legend">${shares.map(g=>`<span><i style="background:${muscleColors[g.group]}"></i>${g.group} · ${pFmt(g.share*100,0)}%</span>`).join('')}</div>`:'<div class="p-empty">Нет тоннажа в периоде.</div>'}</div><div><h3>Подходы в неделю</h3><div class="p-group-bars">${averages.map(g=>`<div class="p-group-row"><span>${g.group}</span><div class="p-group-track"><i style="width:${Math.min(100,g.setsPerWeek/25*100)}%;background:${muscleColors[g.group]}"></i><em></em></div><b>${pFmt(g.setsPerWeek,1)}</b></div>`).join('')}</div><p class="p-guideline">Ориентир: 10–20 подходов в неделю</p></div></div>${imbalances.length?`<div class="p-notice">Перекос объёма: ${imbalances.map(x=>`${x.group} ${x.type==='high'?'выше 40%':'ниже 10%'}`).join(' · ')}</div>`:''}${data.groups.unassigned.length?`<div class="p-notice p-unassigned">${data.groups.unassigned.length} упражн. без группы мышц. <button onclick="toggleGroupEditor()">Назначить группы</button><div id="groupEditor" hidden>${data.groups.unassigned.map(name=>`<label>${pEsc(name)}<select onchange="assignMuscleGroup('${encodeURIComponent(name).replace(/'/g,'%27')}',this.value)"><option value="">Без группы</option>${WorkoutProgress.MUSCLE_GROUPS.map(g=>`<option>${g}</option>`).join('')}</select></label>`).join('')}<button onclick="saveMuscleGroups()">Сохранить группы</button></div></div>`:''}`;}
function toggleGroupEditor(){const e=document.getElementById('groupEditor');e.hidden=!e.hidden;}
function assignMuscleGroup(encoded,value){const name=decodeURIComponent(encoded);if(value)muscleMap[name]=value;else delete muscleMap[name];localMuscleOverrides[name]=value||'';localStorage.setItem('wt_muscle_groups_custom',JSON.stringify(localMuscleOverrides));pendingGroupSync=true;progressCache.clear();}
async function saveMuscleGroups(){if(settings.scriptUrl){try{const r=await fetch(settings.scriptUrl,{method:'POST',body:JSON.stringify({action:'saveGroups',groups:muscleMap})}),j=await r.json();if(j.ok)pendingGroupSync=false;else throw new Error('sync');}catch(e){showToast('Сохранено на устройстве; Sheets пока недоступен');return;}}showToast(settings.scriptUrl?'Группы сохранены в Sheets ✓':'Группы сохранены на устройстве');progressCache.clear();renderStats();}
function renderDigest(title,d){return `<article class="p-card p-digest"><h3>${title}</h3><p>${pDate(d.range.start)} — ${pDate(d.range.end)}</p><div class="p-digest-numbers"><span><b>${d.summary.workouts}</b> тренировок</span><span><b>${pFmt(d.summary.tonnage,0)}</b> кг тоннажа</span></div><small>${d.records.length?`Новые рекорды: ${d.records.slice(0,3).map(r=>pEsc(r.exercise)).join(', ')}`:'Новых рекордов нет'}</small><small>${d.improving?`Растёт: ${pEsc(d.improving.exercise)} (+${pFmt(d.improving.gain,2)} кг 1RM)`:''}</small><small>${d.stalled.length?`Нет роста 4+ нед.: ${pEsc(d.stalled.map(x=>x.exercise).join(', '))}`:'Нет упражнений без роста 4+ недель'}</small></article>`;}
